// Nomes aqui = nomes das funcoes `#[tauri::command]` (snake_case). O helper
// gera `permissions/autogenerated/commands/<cmd>.toml` com os identificadores
// em kebab-case (`allow-set-queue`, ...).
const COMMANDS: &[&str] = &[
    "initialize",
    "set_queue",
    "play",
    "pause",
    "seek_to",
    "next",
    "previous",
    "skip_to_index",
    "get_state",
    "get_queue",
    "add_items",
    "truncate_queue",
    "set_repeat_mode",
    "drain_events",
    "ack_events",
    "register_listener",
    "remove_listener",
    "updater_check",
    "updater_install",
];

fn main() {
    let result = tauri_plugin::Builder::new(COMMANDS)
        .android_path("android")
        .try_build();

    // ao construir documentacao para Android o resultado e sempre Err e
    // irrelevante para o build da doc (mesmo guard dos plugins oficiais)
    if !(cfg!(docsrs) && std::env::var("TARGET").unwrap_or_default().contains("android")) {
        result.unwrap();
    }
}
